// <auto-generated />
using System;
using CP3ConcessionariaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CP3ConcessionariaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520010054_CriarTabelasIniciais")]
    partial class CriarTabelasIniciais
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CP3ConcessionariaAPI.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CLIENTE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<int>("IdConcessionaria")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CONCESSIONARIA");

                    b.Property<string>("NmCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_CLIENTE");

                    b.Property<string>("TIPO_CLIENTE")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)");

                    b.HasKey("IdCliente");

                    b.HasIndex("IdConcessionaria");

                    b.ToTable("CP3_CLIENTE");

                    b.HasDiscriminator<string>("TIPO_CLIENTE").HasValue("Cliente");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CP3ConcessionariaAPI.Models.Concessionaria", b =>
                {
                    b.Property<int>("IdConcessionaria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CONCESSIONARIA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConcessionaria"));

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)")
                        .HasColumnName("CEP");

                    b.Property<string>("DsEndereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DS_ENDERECO");

                    b.Property<string>("NmConcessionaria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_CONCESSIONARIA");

                    b.HasKey("IdConcessionaria");

                    b.ToTable("CP3_CONCESSIONARIA");
                });

            modelBuilder.Entity("CP3ConcessionariaAPI.Models.Contratacao", b =>
                {
                    b.Property<int>("IdContratacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CONTRATACAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContratacao"));

                    b.Property<DateTime>("DtSolicitacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_SOLICITACAO");

                    b.Property<int>("IdCliente")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CLIENTE");

                    b.Property<int>("IdProduto")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PRODUTO");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("STATUS");

                    b.HasKey("IdContratacao");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdProduto");

                    b.ToTable("CP3_CONTRATACAO");
                });

            modelBuilder.Entity("CP3ConcessionariaAPI.Models.Produto", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PRODUTO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduto"));

                    b.Property<string>("NmProduto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_PRODUTO");

                    b.Property<string>("TIPO_PRODUTO")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("NVARCHAR2(13)");

                    b.HasKey("IdProduto");

                    b.ToTable("CP3_PRODUTO");

                    b.HasDiscriminator<string>("TIPO_PRODUTO").HasValue("Produto");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CP3ConcessionariaAPI.Models.PessoaFisica", b =>
                {
                    b.HasBaseType("CP3ConcessionariaAPI.Models.Cliente");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)")
                        .HasColumnName("CPF");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_NASCIMENTO");

                    b.ToTable("CP3_CLIENTE");

                    b.HasDiscriminator().HasValue("PF");
                });

            modelBuilder.Entity("CP3ConcessionariaAPI.Models.PessoaJuridica", b =>
                {
                    b.HasBaseType("CP3ConcessionariaAPI.Models.Cliente");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("CNPJ");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("RAZAO_SOCIAL");

                    b.ToTable("CP3_CLIENTE");

                    b.HasDiscriminator().HasValue("PJ");
                });

            modelBuilder.Entity("CP3ConcessionariaAPI.Models.Financiamento", b =>
                {
                    b.HasBaseType("CP3ConcessionariaAPI.Models.Produto");

                    b.Property<int>("PrazoMeses")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NR_PRAZO_MESES");

                    b.Property<decimal>("TaxaJuros")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("TX_JUROS");

                    b.Property<decimal>("ValorEntrada")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("VL_ENTRADA");

                    b.Property<decimal>("ValorParcela")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("VL_PARCELA");

                    b.Property<decimal>("ValorVeiculo")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("VL_VEICULO");

                    b.ToTable("CP3_PRODUTO");

                    b.HasDiscriminator().HasValue("FINANCIAMENTO");
                });

            modelBuilder.Entity("CP3ConcessionariaAPI.Models.Cliente", b =>
                {
                    b.HasOne("CP3ConcessionariaAPI.Models.Concessionaria", "Concessionaria")
                        .WithMany()
                        .HasForeignKey("IdConcessionaria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Concessionaria");
                });

            modelBuilder.Entity("CP3ConcessionariaAPI.Models.Contratacao", b =>
                {
                    b.HasOne("CP3ConcessionariaAPI.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CP3ConcessionariaAPI.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
